### ISSUE TITLE
Clock can be right twice on November 5

### ISSUE THREAD

**Issue by WoogieNoogie** [JuriKiin/NotAlwaysRightTwice#1]
If the random seed generated from midnight - 2AM on November 5 causes the time to show anything from 1AM - 2AM as this hour repeats due to daylight savings time.

**Comment by JuriKiin** [comment]
Nice find! Feel free to make a PR to adjust this! Contributing to FOSS is always very important

**Comment by JuriKiin** [comment]
This should be hackily addressed in #2
